# -*- coding: utf-8 -*-
"""Part -4 Visualizing Named Entity Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17kz1Nf3-vzPoyksjldrOI7Whmwpjm5-o

# Visualizing Named Entity Recognition
"""

import spacy

nlp = spacy.load(u'en_core_web_sm')

from spacy import displacy

doc = nlp(u'Over the last 6 months apple sold more than 1 million\
 iphones from India to world market for a profit of $7 billion.'\
u'Apple is planning to do $30 billion business per year by 2027 in India')

displacy.render(doc,style='ent')

# line by line

for sent in doc.ents:
    displacy.render(nlp(sent.text),style='ent')

options = {'ents':['PRODUCT','ORG','DATE']}

displacy.render(doc,style='ent',options=options)

colors = {'ORG':'red'}
options = {'ents':['PRODUCT','ORG','DATE'],'colors':colors}

displacy.render(doc,style='ent',options=options)

colors = {'ORG':'radial-gradient(yellow,blue)'}
options = {'ents':['PRODUCT','ORG','DATE'],'colors':colors}

displacy.render(doc,style='ent',options=options)

colors = {'ORG':'linear-gradient(yellow,red,black)'}
options = {'ents':['PRODUCT','ORG','DATE'],'colors':colors}

displacy.render(doc,style='ent',options=options)

colors = {'ORG':'linear-gradient(90deg,yellow,red,black)'}
options = {'ents':['PRODUCT','ORG','DATE'],'colors':colors}

displacy.render(doc,style='ent',options=options)

displacy.serve(doc,style='ent',options=options)





