# -*- coding: utf-8 -*-
"""Part  - 5 Stopwords.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pVkK3DAz7QGo_KTN3pr8ELbwS7qYFSk9

# Stopwords

Words like "a" and "the" appear so frequently that they don't require
tagging as thoroughly as nouns , verbs and modifiers.

These are stopwords and they can be filtered from the text to be
processed.

Stop words are just common words that don't provide any additional
information, and sometimes they can actually damage NLP analysis.

Spacy holds a  built in list of some 326 English stop words.
"""

import spacy

nlp=spacy.load('en_core_web_sm')

# English core web small language

stop_words = nlp.Defaults.stop_words
stop_words

len(stop_words)

# check if word in stop words list or not

nlp.vocab['is'].is_stop

nlp.vocab['are'].is_stop

nlp.vocab['malav'].is_stop

nlp.vocab['joshi'].is_stop

# add stop word in stop words list

# When working with text data, like text messages, a lot of us
# use BTW for by the way
# SO may be we want to consider this as stop word for a particular dataset.

nlp.Defaults.stop_words.add('btw')

nlp.vocab['btw'].is_stop

nlp.vocab['btw'].is_stop=True

len(nlp.Defaults.stop_words)

# earlier it was 326 now its 327

# Remove stop word

nlp.Defaults.stop_words.remove('beyond')

nlp.vocab['beyond'].is_stop

nlp.vocab['beyond'].is_stop=False

len(nlp.Defaults.stop_words)