# -*- coding: utf-8 -*-
"""Part 2- Working with PDFs Files with Pythonipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T0ONFRErw8oO7_WjVVdKQPeL8D_RBJg-

#PDFs file


---

1.) Import PyPDF2 library

2.) Not all PDFs have text that can be extracted!

3.) Some PDFs are created through scanning, instead of being expireted from text editor like word.

4.) These scanned PDFs are more like image files, making it much harder to extract the text.

5.) Often this requires specialized software!

6.) The PyPD2 library is made to extract text from PDF files directly created from word processor, but keep in mind, not all word processors created PDFs with extractable text!

7.)
"""

!pip install PyPDF2
import PyPDF2 # Now PyPDF2 module should be available

my_pdf_file=open("/content/US_Declaration.pdf",mode="rb")

# rb = reading in binary method
# We need that because it's no longer a normal text file.
# It's a PDF file.

# Once we read file.
# convert it into a PDF file reder object.

pdf_reader=PyPDF2.PdfReader(my_pdf_file)

len(pdf_reader.pages)

# No. of pages in pdf.

# Extract text page by page.

page_one = pdf_reader.pages[0]
page_one.extract_text()

print(page_one.extract_text())

# we can save text as well.

my_pdf_file.close()

"""
Sometimes if needed new page can be added to pdf.
But we cannot directly write a Python string text onto
a PDF because of the differences between a single
string type of Python vs. the variety of fonts and
placements and pther parameters that a PDF could have.

what we can do is copy pages and append pages
to the end.
So copy a page from another PDF or the same PDF
and then append it to the end of the current
PDF you are working with.

What we can't do is take a Python String
and suddenly insert it somewhere into the PDF

"""

# Let's add a page to PDF.
pdf_file= open("/content/US_Declaration.pdf",mode="rb")

pdf_reader=PyPDF2.PdfReader(pdf_file)

page_one=pdf_reader.pages[0]

page_one.extract_text()

pdf_writer = PyPDF2.PdfWriter()

# it will add new pages

new_page=pdf_writer.add_page(page_one)

new_pdf_output = open("NLP.pdf","wb")

# wb= write binary

pdf_writer.write(new_pdf_output)

new_pdf_output.close()
pdf_file

new_pdf_output = open("NLP.pdf","rb")

pdf_reader=PyPDF2.PdfReader(new_pdf_output)

len(pdf_reader.pages)

page_one=pdf_reader.pages[0]

page_one.extract_text()

# Grabbing all the PDFs from the particular file.

f = open("/content/US_Declaration.pdf","rb")

pdf_text=[]

pdf_reader=PyPDF2.PdfReader(f)

for p in range(len(pdf_reader.pages)):

    page = pdf_reader.pages[p]

    pdf_text.append(page.extract_text())


f.close()

pdf_text

len(pdf_text)