# -*- coding: utf-8 -*-
"""Project - 2 Movie Reviews Classification .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VwZpoXYLa0OLyIqGAEcxRiXa95VdHA7

# Movie Review Classification

Goal it to check whether movie review is positive/negative using dataset.
"""

# Import libraries

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix,classification_report

# Load the dataset

data = pd.read_csv("/content/moviereviews.tsv",sep="\t")
data.head()

data.info()

data['review'][1]

# Check for missing values

data.isnull().sum()

# remove missing values

data.dropna(inplace=True)
# remove permenant

data.isnull().sum()

# Example to check empty sting

empty = '  '
empty.isspace()

blanks = []

#(index,label,review text)

for i,lb,rb in data.itertuples():

    if rb.isspace():
        blanks.append(i)

print(len(blanks))

# 27 places where reviews are empty string

# drop empty reviews.

data.drop(blanks,inplace=True)

data.info()

X = data['review']
y = data['label']

# divide data in train and test

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,
                                                 random_state=42)

X_train.shape

X_test.shape

y_train.shape

y_test.shape

# build a pipeline

pipeline= Pipeline([("tfidf",TfidfVectorizer()),
                    ("model",LinearSVC())])
pipeline.fit(X_train,y_train)

pred = pipeline.predict(X_test)
pred

# confusion matrix

cm = confusion_matrix(y_test,pred)
cm

report= classification_report(y_test,pred,output_dict=True)
report

report= pd.DataFrame(report).transpose()
report

# LinearSVC model gives 84% accuracy

review="Singham Again is a must-watch for fans of the action genre and the cop universe that Rohit Shetty has so meticulously built. It’s unapologetically loud, patriotic, and larger-than-life, offering fans everything they expect and more. Despite a few predictable moments, the film’s sheer energy and visual spectacle make up for it, delivering a thoroughly entertaining experience."
review

pipeline.predict([review])

review="Last year I loved the delightful indie zombie Christmas musical Anna and the Apocalypse. It was creative, funny and sweet. It even made Best Films of 2018. So when I saw a trailer for The Dead Don’t Die I got very excited. The trailer was hilarious, and I love the cast. My hope was it was going to be a Wes Anderson meets Zombieland film. Unfortunately I was very disappointed. The Dead Don’t Die was an unfunny, self-indulgent, frustrating experience. The cast is woefully wasted, and they strain for the few laughs the script offers. The metaphors are also rammed in to the ground by narrators and characters breaking the 4th wall. It is my first film from director Jim Jarmusch but the critics at Cannes and other places don’t seem to be enjoying it either, so it appears to be a just a big miss. It’s frustrating because it had so much potential and it all falls flat."
review

pipeline.predict([review])